version: '3.8'

services:
  movie-search-service:
    image: movie-search-service:1.0
    build: 
      context: .  # Build context for the app
      dockerfile: Dockerfile.dev
      args:
        APP_PORT: ${APP_PORT}
    container_name: movie-search-service
    # ports:
      # - "${APP_PORT}:${APP_PORT}"
      # - "${DEBUGGER_PORT}:${DEBUGGER_PORT}" # port for debugger 
    volumes:
      - .:/app  # Mount the current directory to /app in the container for development
    env_file:
      - ./.env.dev
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - MONGODB_PORT=${MONGODB_PORT}
      - DEBUGGER_PORT=${DEBUGGER_PORT}
      - JWT_KEY=${JWT_KEY}
    networks:
      - app-network

networks:
  app-network:
    external: true  